name: corrected-resubmission
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - rdkit
  - openbabel
  - pdbfixer
  - openmm
  - biopython
  - numpy
  - pandas
  - scipy
  - matplotlib
  - pillow
  - requests
